using Microsoft.EntityFrameworkCore;
using PeopleGrid.Domain.Entities;

namespace PeopleGrid.Application.Abstractions;

public interface IApplicationDbContext : IAsyncDisposable
{
    DbSet<User> Users { get; set; }
    DbSet<UserProfile> UserProfiles { get; set; }
    DbSet<UserSession> UserSessions { get; set; }
    DbSet<RefreshToken> RefreshTokens { get; set; }
    DbSet<PasswordResetToken> PasswordResetTokens { get; set; }
    DbSet<PasswordHistory> PasswordHistories { get; set; }
    DbSet<LoginAttempt> LoginAttempts { get; set; }
    DbSet<Role> Roles { get; set; }
    DbSet<Permission> Permissions { get; set; }
    DbSet<UserRole> UserRoles { get; set; }
    DbSet<RolePermission> RolePermissions { get; set; }
    DbSet<Department> Departments { get; set; }
    DbSet<UserManagerAssignment> UserManagerAssignments { get; set; }
    DbSet<Unit> Units { get; set; }
    DbSet<Branch> Branches { get; set; }
    DbSet<JobTitle> JobTitles { get; set; }
    DbSet<GradeLevel> GradeLevels { get; set; }
    DbSet<EmploymentType> EmploymentTypes { get; set; }
    DbSet<CompanyProfile> CompanyProfiles { get; set; }
    DbSet<ApprovalLevel> ApprovalLevels { get; set; }
    DbSet<LeaveType> LeaveTypes { get; set; }
    DbSet<PublicHoliday> PublicHolidays { get; set; }
    DbSet<SystemParameter> SystemParameters { get; set; }
    DbSet<Employee> Employees { get; set; }
    DbSet<EmployeePersonalInfo> EmployeePersonalInfos { get; set; }
    DbSet<EmployeeContactInfo> EmployeeContactInfos { get; set; }
    DbSet<EmployeeEmploymentInfo> EmployeeEmploymentInfos { get; set; }
    DbSet<EmployeeBankInfo> EmployeeBankInfos { get; set; }
    DbSet<EmployeeNextOfKin> EmployeeNextOfKin { get; set; }
    DbSet<EmployeeEmergencyContact> EmployeeEmergencyContacts { get; set; }
    DbSet<EmployeeJobHistory> EmployeeJobHistories { get; set; }
    DbSet<EmployeeStatusHistory> EmployeeStatusHistories { get; set; }
    DbSet<EmployeeDocument> EmployeeDocuments { get; set; }
    DbSet<DocumentType> DocumentTypes { get; set; }
    DbSet<DocumentAccessRule> DocumentAccessRules { get; set; }
    DbSet<DocumentVerificationHistory> DocumentVerificationHistories { get; set; }
    DbSet<DocumentStorageReference> DocumentStorageReferences { get; set; }
    DbSet<HRRequest> HRRequests { get; set; }
    DbSet<HRRequestType> HRRequestTypes { get; set; }
    DbSet<HRRequestAttachment> HRRequestAttachments { get; set; }
    DbSet<HRRequestStatusHistory> HRRequestStatusHistories { get; set; }
    DbSet<ApprovalFlow> ApprovalFlows { get; set; }
    DbSet<ApprovalStep> ApprovalSteps { get; set; }
    DbSet<ApprovalRequest> ApprovalRequests { get; set; }
    DbSet<ApprovalRule> ApprovalRules { get; set; }
    DbSet<ApprovalInstance> ApprovalInstances { get; set; }
    DbSet<ApprovalInstanceStep> ApprovalInstanceSteps { get; set; }
    DbSet<ApprovalAction> ApprovalActions { get; set; }
    DbSet<ApprovalEscalation> ApprovalEscalations { get; set; }
    DbSet<LeaveRequest> LeaveRequests { get; set; }
    DbSet<LeaveEntitlement> LeaveEntitlements { get; set; }
    DbSet<LeaveBalance> LeaveBalances { get; set; }
    DbSet<LeaveRequestDate> LeaveRequestDates { get; set; }
    DbSet<LeaveApprovalAction> LeaveApprovalActions { get; set; }
    DbSet<LeaveBalanceAdjustment> LeaveBalanceAdjustments { get; set; }
    DbSet<WorkCalendar> WorkCalendars { get; set; }
    DbSet<AttendanceRecord> AttendanceRecords { get; set; }
    DbSet<AttendanceEvent> AttendanceEvents { get; set; }
    DbSet<AttendanceCorrectionRequest> AttendanceCorrectionRequests { get; set; }
    DbSet<AttendanceApprovalAction> AttendanceApprovalActions { get; set; }
    DbSet<WorkSchedule> WorkSchedules { get; set; }
    DbSet<Shift> Shifts { get; set; }
    DbSet<AttendanceSource> AttendanceSources { get; set; }
    DbSet<OvertimeRecord> OvertimeRecords { get; set; }
    DbSet<AbsenceRecord> AbsenceRecords { get; set; }
    DbSet<OnboardingTemplate> OnboardingTemplates { get; set; }
    DbSet<OnboardingTemplateItem> OnboardingTemplateItems { get; set; }
    DbSet<OnboardingPlan> OnboardingPlans { get; set; }
    DbSet<OnboardingTask> OnboardingTasks { get; set; }
    DbSet<OnboardingDocument> OnboardingDocuments { get; set; }
    DbSet<PolicyAcknowledgement> PolicyAcknowledgements { get; set; }
    DbSet<EmployeeAssetAssignment> EmployeeAssetAssignments { get; set; }
    DbSet<ProbationRecord> ProbationRecords { get; set; }
    DbSet<DisciplinaryCase> DisciplinaryCases { get; set; }
    DbSet<DisciplinaryResponse> DisciplinaryResponses { get; set; }
    DbSet<DisciplinaryReview> DisciplinaryReviews { get; set; }
    DbSet<DisciplinaryAction> DisciplinaryActions { get; set; }
    DbSet<WarningLetter> WarningLetters { get; set; }
    DbSet<SuspensionRecord> SuspensionRecords { get; set; }
    DbSet<DisciplinaryEscalation> DisciplinaryEscalations { get; set; }
    DbSet<DisciplinaryAttachment> DisciplinaryAttachments { get; set; }
    DbSet<ExitCase> ExitCases { get; set; }
    DbSet<ResignationRequest> ResignationRequests { get; set; }
    DbSet<ExitApprovalAction> ExitApprovalActions { get; set; }
    DbSet<ExitClearanceItem> ExitClearanceItems { get; set; }
    DbSet<ExitHandoverRecord> ExitHandoverRecords { get; set; }
    DbSet<ExitInterviewResponse> ExitInterviewResponses { get; set; }
    DbSet<ExitAssetReturn> ExitAssetReturns { get; set; }
    DbSet<FinalSettlementStatus> FinalSettlementStatuses { get; set; }
    DbSet<SalaryStructure> SalaryStructures { get; set; }
    DbSet<PayrollItem> PayrollItems { get; set; }
    DbSet<EmployeePayrollItem> EmployeePayrollItems { get; set; }
    DbSet<PayrollRun> PayrollRuns { get; set; }
    DbSet<PayrollRunEmployee> PayrollRunEmployees { get; set; }
    DbSet<PayrollEarning> PayrollEarnings { get; set; }
    DbSet<PayrollDeduction> PayrollDeductions { get; set; }
    DbSet<TaxRule> TaxRules { get; set; }
    DbSet<PensionRule> PensionRules { get; set; }
    DbSet<EmployeeLoan> EmployeeLoans { get; set; }
    DbSet<LoanRepayment> LoanRepayments { get; set; }
    DbSet<Payslip> Payslips { get; set; }
    DbSet<PayrollApprovalAction> PayrollApprovalActions { get; set; }
    DbSet<PayrollAuditHistory> PayrollAuditHistories { get; set; }
    DbSet<PerformanceCycle> PerformanceCycles { get; set; }
    DbSet<PerformanceTemplate> PerformanceTemplates { get; set; }
    DbSet<EmployeeGoal> EmployeeGoals { get; set; }
    DbSet<EmployeeKpi> EmployeeKpis { get; set; }
    DbSet<SelfAssessment> SelfAssessments { get; set; }
    DbSet<ManagerAssessment> ManagerAssessments { get; set; }
    DbSet<HrPerformanceReview> HrPerformanceReviews { get; set; }
    DbSet<PerformanceRating> PerformanceRatings { get; set; }
    DbSet<PromotionRecommendation> PromotionRecommendations { get; set; }
    DbSet<PerformanceImprovementPlan> PerformanceImprovementPlans { get; set; }
    DbSet<PerformanceHistory> PerformanceHistories { get; set; }
    DbSet<JobOpening> JobOpenings { get; set; }
    DbSet<VacancyPublication> VacancyPublications { get; set; }
    DbSet<Candidate> Candidates { get; set; }
    DbSet<CandidateApplication> CandidateApplications { get; set; }
    DbSet<CandidateDocument> CandidateDocuments { get; set; }
    DbSet<InterviewSchedule> InterviewSchedules { get; set; }
    DbSet<InterviewPanelMember> InterviewPanelMembers { get; set; }
    DbSet<InterviewFeedback> InterviewFeedbacks { get; set; }
    DbSet<OfferLetter> OfferLetters { get; set; }
    DbSet<RecruitmentStatusHistory> RecruitmentStatusHistories { get; set; }
    DbSet<TrainingProgram> TrainingPrograms { get; set; }
    DbSet<TrainingSchedule> TrainingSchedules { get; set; }
    DbSet<TrainingNomination> TrainingNominations { get; set; }
    DbSet<TrainingApprovalAction> TrainingApprovalActions { get; set; }
    DbSet<TrainingAttendance> TrainingAttendance { get; set; }
    DbSet<TrainingFeedback> TrainingFeedback { get; set; }
    DbSet<TrainingCertificate> TrainingCertificates { get; set; }
    DbSet<Skill> Skills { get; set; }
    DbSet<EmployeeSkill> EmployeeSkills { get; set; }
    DbSet<TrainingCost> TrainingCosts { get; set; }
    DbSet<TrainingHistory> TrainingHistories { get; set; }
    DbSet<ReportDefinition> ReportDefinitions { get; set; }
    DbSet<ReportPermission> ReportPermissions { get; set; }
    DbSet<ReportExportJob> ReportExportJobs { get; set; }
    DbSet<ReportExportFile> ReportExportFiles { get; set; }
    DbSet<DashboardCard> DashboardCards { get; set; }
    DbSet<DashboardRoleMapping> DashboardRoleMappings { get; set; }
    DbSet<DashboardMetricSnapshot> DashboardMetricSnapshots { get; set; }
    DbSet<ReportAuditLog> ReportAuditLogs { get; set; }
    DbSet<Notification> Notifications { get; set; }
    DbSet<NotificationTemplate> NotificationTemplates { get; set; }
    DbSet<NotificationDeliveryLog> NotificationDeliveryLogs { get; set; }
    DbSet<NotificationPreference> NotificationPreferences { get; set; }
    DbSet<AuditLog> AuditLogs { get; set; }
    DbSet<AuditLogDetail> AuditLogDetails { get; set; }
    DbSet<SystemSetting> SystemSettings { get; set; }

    Task<int> SaveChangesAsync(CancellationToken cancellationToken = default);
}

public interface IApplicationDbContextFactory
{
    IApplicationDbContext CreateDbContext(string connectionString);
}
